### PR TITLE
Added mug and circle versions of logo

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Here are SVG and PNG versions used for the 2018 mugs.

And a circular one.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks for cleaning this up.

**Comment by beckermr** [comment]
Thanks for all the work making the logos!

**Comment by jakirkham** [comment]
It might be worth doing another run of mugs. Those were pretty popular from what I recall and people do ask about these periodically.

**Comment by ChrisBarker-NOAA** [comment]
I did that for the SciPy conference -- so maybe again this year? (I'm not totally sure I'm going, but I hope so)

I do think it makes sense to do it where a lot of conda blacksmiths converge -- certainly other meetings might be good opportunities as well -- if anyone has any ideas, let's make it happen!

**Pull request merged**
